# Site settings
title: mokagio's tech journal
email: giovanni.lodi42@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This place is a collector of random findings regarding little details of the software development craft.
baseurl: "/tech-journal"
url: "http://mokagio.github.com"
twitter_username: mokagio
github_username:  mokagio

# Build settings
markdown: kramdown
highlighter: pygments

kramdown:
  auto_ids:      true
  footnote_nr:   1
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  use_coderay:   false
  input:         GFM
  use_coderay:   true
  coderay:
    coderay_line_numbers:  nil

# Disqus
comments: true
